"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

from api.configurations.base import *

from api.configurations.allowed_hosts import ALLOWED_HOSTS
from api.configurations.apps import INSTALLED_APPS
from api.configurations.middlewares import MIDDLEWARE
from api.configurations.database import DATABASES

from api.configurations.templates import TEMPLATES
from api.configurations.auth import AUTH_PASSWORD_VALIDATORS

from api.configurations.rest_framework import *
from api.configurations.cors import *
