"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

from api.configurations.base import *

from api.configurations.allowed_hosts import *
from api.configurations.apps import *
from api.configurations.middlewares import *
from api.configurations.database import *

from api.configurations.templates import *
from api.configurations.auth import *

from api.configurations.rest_framework import *
from api.configurations.cors import *
